In [1]:
import pandas as pd
import numpy as np

In [18]:
trm_ktrials = pd.read_excel("recreated_data.xlsx", sheet_name="ktrials", nrows=25)
trm_ftrials = pd.read_excel("recreated_data.xlsx", sheet_name="ftrials", nrows=25)

In [3]:
psychopy_data = pd.read_excel("PsychoPy_data.xlsx", sheet_name="PsychoPy_R", nrows=25)

In [19]:
trm_ktrials.rename(columns={'k_resp.ke…': 'k_resp.keys_raw'}, inplace=True)

In [5]:
COLS_FOR_KTRIALS = ['order', 'k_resp.keys_raw']
COLS_FOR_FTRIALS = ['order', 'f_slider.response_mean', 'f_slider.response_raw']
COLS_FOR_CTRIALS = ['order', 'c_slider.response_mean', 'c_slider.response_raw']
COLS_FOR_PSYCHOPY = {'ktrials': ['kOrder', 'kResp'],
                     'ftrials': ['fOrder', 'fSlider'],
                     'ctrials': ['cOrder', 'cSlider']}

In [6]:
trm_ktrials.columns

Index(['img_file', 'Race', 'Gender', 'Option', 'n', 'k_ISI.start…',
       'k_ISI.start….1', 'k_ISI.stop…', 'k_ISI.stop….1', 'k_cand.st…',
       'k_cand.st….1', 'k_cand…', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'k_cross.st…', 'k_cross.st….1', 'k_cross.st….2', 'k_cross.st….3',
       'k_resp.keys_raw', 'k_resp.rt…', 'k_resp.sta…', 'k_resp.sta….1',
       'k_resp.sta….2', 'k_resp.sto…', 'k_text1.st…', 'k_text1.st….1',
       'k_text1.st….2', 'k_text1.st….3', 'k_text2.st…', 'k_text2.st….1',
       'k_text2.st….2', 'k_text2.st….3', 'order'],
      dtype='str')

In [20]:
trm_ktrials['img_file']  = trm_ktrials['img_file'].str[-7:]

In [21]:
trm_ktrials[['img_file', 'Race', 'Gender'] + COLS_FOR_KTRIALS].head(5)

  img_file    Race Gender  order k_resp.keys_raw
0  BM1.png   Black    Man     21               d
1  BM2.png   Black    Man     10               d
2  BW1.png   Black  Woman      0               d
3  BW2.png   Black  Woman     12               d
4  LM1.png  Latino    Man      9               d

In [8]:
psychopy_data.head()

,StudyID,img_file,Race,Gender,Option,kOrder,kResp,fOrder,fSlider,cOrder,cSlider,fZ,cZ
0,9994,BM1.png,Black,Man,1,NaN,NaN,4,1.613333,11,2.180000,1.058364,1.092048
1,9994,BM2.png,Black,Man,2,NaN,NaN,20,1.686667,7,1.346667,1.135614,-0.143300
2,9994,BW1.png,Black,Woman,1,NaN,NaN,18,1.433333,17,0.746667,0.868754,-1.032751
3,9994,BW2.png,Black,Woman,2,NaN,NaN,22,0.980000,19,1.353333,0.391218,-0.133418
4,9994,LM1.png,Latino,Man,1,NaN,NaN,1,0.466667,0,1.993333,-0.149523,0.815330

In [22]:
keys = ['img_file',	'Race',	'Gender']

In [23]:
lookup_series = trm_ktrials.set_index(keys)['order']

In [24]:
psychopy_data['kOrder'] = psychopy_data.set_index(keys).index.map(lookup_series)

In [25]:
psychopy_data.head()

,StudyID,img_file,Race,Gender,Option,kOrder,kResp,fOrder,fSlider,cOrder,cSlider,fZ,cZ
0,9994,BM1.png,Black,Man,1,21,NaN,4,1.613333,11,2.180000,1.058364,1.092048
1,9994,BM2.png,Black,Man,2,10,NaN,20,1.686667,7,1.346667,1.135614,-0.143300
2,9994,BW1.png,Black,Woman,1,0,NaN,18,1.433333,17,0.746667,0.868754,-1.032751
3,9994,BW2.png,Black,Woman,2,12,NaN,22,0.980000,19,1.353333,0.391218,-0.133418
4,9994,LM1.png,Latino,Man,1,9,NaN,1,0.466667,0,1.993333,-0.149523,0.815330

In [26]:
lookup_series_resp = trm_ktrials.set_index(keys)['k_resp.keys_raw']
psychopy_data['kResp'] = psychopy_data.set_index(keys).index.map(lookup_series_resp)

In [27]:
psychopy_data.head()

,StudyID,img_file,Race,Gender,Option,kOrder,kResp,fOrder,fSlider,cOrder,cSlider,fZ,cZ
0,9994,BM1.png,Black,Man,1,21,d,4,1.613333,11,2.180000,1.058364,1.092048
1,9994,BM2.png,Black,Man,2,10,d,20,1.686667,7,1.346667,1.135614,-0.143300
2,9994,BW1.png,Black,Woman,1,0,d,18,1.433333,17,0.746667,0.868754,-1.032751
3,9994,BW2.png,Black,Woman,2,12,d,22,0.980000,19,1.353333,0.391218,-0.133418
4,9994,LM1.png,Latino,Man,1,9,d,1,0.466667,0,1.993333,-0.149523,0.815330